### ISSUE TITLE
Microsoft Exchange Transport will not start when Exchange DkimSigner is enabled

### ISSUE THREAD

**Issue by ModernAesthetics** [Pro/dkim-exchange#266]
### Versions

- **Windows Server Version**: Windows Server 2008 R2 Standard
- **Exchange Version**: Exchange Server 2010 14.3.123.4
- **Installed DKIM Exchange Version**: 3.2.0

### Description

Microsoft Exchange Transport will not start when Exchange DkimSigner is enabled.

### Steps to Reproduce

Download the dkim-exchange-3.2.0.zip and extract to Desktop
Open "Exchange Management Shell"
Powershell CMD: Set-ExecutionPolicy Unrestricted
CD into the folder where the zip has been extracted.
Execute the install script .\install.ps1
Run Configuration.DkimSigner.exe and configure Domain
Enter to finish (Transport will not start and Conifuration.DkimSigner.exe hangs up)

If I disable the Exchange DkimSigner in the configuration transport starts just fine.

**Comment by ModernAesthetics** [comment]
Updated to the latest rollup for Exchange 2010 and still the same results.

**Comment by sarthurdev** [comment]
Hey @ModernAesthetics 

I just spun up a test 2010 environment and can't seem to reproduce the issue using the GUI installer on pre-release version. What .NET framework versions do you have installed?

**Comment by mattidp** [comment]
I have .NET 4.7.2 and it doesn't work either.

**Comment by mattidp** [comment]
Configuration.DkimSigner.exe also displays errors about getting Exchange version and running powershell.

**Comment by sarthurdev** [comment]
Are you using the latest pre-release and getting this issue?

**Comment by mattidp** [comment]
I am getting with both 1.1 and pre-release.

Best Regards,
Matthew J. Rainoff
www.IDP.Net<http://www.IDP.Net>
703-591-7118
571-436-6327




On Sun, Sep 15, 2019 at 11:42 AM -0400, "Simon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using the latest pre-release and getting this issue?

**Comment by mattidp** [comment]
When I run Configuration.DkimSigner.exe:
First error is "Couldn't determine installed Exchange Version: Couldn't initialize PowerShell runspace."

**Comment by mattidp** [comment]
What would stop PowerShell runspace?  That seems to be the key to all dysfunction.

**Comment by mattidp** [comment]
Here is what I get when I try to do anything with Configuration.DkimSigner.exe even in Visual Studio Debug mode:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Configuration.DkimSigner.Exchange.ExchangeServerException: Couldn't initialize PowerShell runspace.
   at Configuration.DkimSigner.Exchange.ExchangeServer.GetInstalledVersion() in C:\Users\Administrator\Desktop\dkim-exchange\Src\Configuration.DkimSigner\Exchange\ExchangeServer.cs:line 33
   at Configuration.DkimSigner.InstallWindow.<CheckExchangeInstalled>b__13_0() in C:\Users\Administrator\Desktop\dkim-exchange\Src\Configuration.DkimSigner\InstallWindow.cs:line 145
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Configuration.DkimSigner.InstallWindow.<CheckExchangeInstalled>d__13.MoveNext() in C:\Users\Administrator\Desktop\dkim-exchange\Src\Configuration.DkimSigner\InstallWindow.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by mattidp** [comment]
Same with all versions including 8/29/2019 build/

**Comment by sarthurdev** [comment]
The only timed I reproduced that error was on a server without Exchange installed. The section of code where it's throwing the exception is where it runs the cmdlet "Get-ExchangeServer" after loading the Exchange Powershell to fetch the Exchange version.

Is the Exchange Management Shell working properly on the server?

**Comment by mattidp** [comment]
Yes, the Exchange Management Shell is working properly, but the C# Powershell run method is not. It must be something on my machine since it’s consistent across all builds. I just don’t know how to report the problem to Microsoft. I have support tokens. What specific .NET Powershell object could cause that?

**Comment by mattidp** [comment]
I tested the classes that are called to get Get-ExchangeServer to work and it fails on every Windows 2008 R2 Server with Exchange 2010.  All servers have fully operational Exchange Powershell.

**Comment by mattidp** [comment]
Works fine on Exchange 2013.

**Comment by mattidp** [comment]
[DKIMTEST.exe.zip](https://github.com/Pro/dkim-exchange/files/3622695/DKIMTEST.exe.zip)

Test for Get-ExchangeServer working.

**Comment by sarthurdev** [comment]
![image](https://user-images.githubusercontent.com/965089/65068245-8b752280-d988-11e9-8242-0b10e301f1ee.png)

In my VM running the eval of 2008 R2 + Exchange 2010 SP3, I can't reproduce this issue.

**Comment by mattidp** [comment]
So am I using the wrong version of your program or what?  The console app I built was from the 4/29 code and an older dll for automation. If you run it it should return the Get  I tried it on two Exchange 2010 servers, one VM and one physical box and both failed. The console app I wrote used the code from GitHub and should return the Get-ExchangeServer value.

**Comment by mattidp** [comment]
Can you please direct me to the link to download the latest source or builds?  Thanks for trying.

**Comment by sarthurdev** [comment]
Builds and source for versions are here: https://github.com/Pro/dkim-exchange/releases

**Comment by boscorelly** [comment]
@mattidp the problem must not be investigated as the only one thng to do is upgrade to 2016 server and exchange at least.

**Comment by mattidp** [comment]
> @mattidp the problem must not be investigated as the only one thng to do is upgrade to 2016 server and exchange at least.

If the program supports 2008 R2 and Exchange 2010 as it appears to, I would prefer to find out why on two different machines installed at different times the same symptoms occur.  Upgrading OS and especially Exchange Server is not a small task.

**Comment by boscorelly** [comment]
Depending on how much mailboxes you have, it’s really quick ! Less than 24h from 2010 to 2016, and 80 mailboxes (1Tb). 
You have 3 months to migrate. 
Don’t waste your time...

**Comment by mattidp** [comment]
Thanks for your opinion.  If my customers want to spend that much money to get DKIM to work, you are correct. You must not pay for software :)  SPF works without add-on functionality.

**Comment by boscorelly** [comment]
You MUST inform them the risks after the 14 jan 2020.

being on 2008 past this date it suicidal...

**Comment by marcwaz** [comment]
Hello, I have exactly the same issue.
I mean after the installation, the transport service is not restarting (unless I disable the Exchange DkimSigner).
In the event log I get the watson error:
Le rapport Watson est prêt à être envoyé pour l'ID de processus : 13516, avec les paramètres : E12, c-RTL-AMD64, 14.01.0438.000, edgetransport, ExchangeDkimSigner, E.D.DkimSigningRoutingAgentFactory..ctor, S.Reflection.TargetInvocationException, 6d6d, 03.02.0000.-001.
ErrorReportingEnabled : False

**Comment by DJBenson** [comment]
Please try the latest release and report back. v3.2.3 has been published today.

**Comment by mattidp** [comment]
Still does not work, but the good new is it doesn't crash Exchange Transport service. Just won't recognize Exchange. Still the problem with Powershell runspace.
![ExchangeDKIMSigner](https://user-images.githubusercontent.com/17870285/71920840-a3e69400-3155-11ea-939b-a61cfaaaa7c6.jpg)

**Comment by DJBenson** [comment]
So it doesn't seem to be a specific problem with the application then? Given you've written your own console application which also fails, I think that rules out a specific bug with the software but doesn't help you unfortunately.

Did you already try running the command in EMS, and if so, what was the outcome?

>Get-ExchangeServer -Identity <hostname>| fl AdminDisplayVersion

**Comment by mattidp** [comment]
[PS] C:\Windows>Get-ExchangeServer -Identity | fl AdminDisplayVersion

Get-ExchangeServer : Missing an argument for parameter 'Identity'. Specify a parameter of type 'System.Object' and try
again.
At line:1 char:29
+ Get-ExchangeServer -Identity <<<<  | fl AdminDisplayVersion
    + CategoryInfo          : InvalidArgument: (:) [Get-ExchangeServer], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Get-ExchangeServer

**Comment by mattidp** [comment]
Works without the –Identity :


[PS] C:\Windows>Get-ExchangeServer | fl AdminDisplayVersion


AdminDisplayVersion : Version 14.3 (Build 123.4)

**Comment by DJBenson** [comment]
Sorry GitHub stripped some of my question:

> Get-ExchangeServer -Identity **HOSTNAME** | fl AdminDisplayVersion

**Comment by mattidp** [comment]
-Identity is not part of Get-ExchangeServer in both Exchange 2010 AND Exchange 2013.

**Comment by mattidp** [comment]
Ok, sorry -Identity ONLY works when you specify the correct hostname, on all versions.

**Comment by DJBenson** [comment]
Well that could be the problem. There’s two calls to Get-ExchangeServer, one in ExchangeServers.cs (which is referenced by the configuration tool) and once in install.ps1, both pass the -Identity parameter.

I’ll take a look ASAP.

**Comment by mattidp** [comment]
That would make sense. For the local machine -Identity is unnecessary.

**Comment by DJBenson** [comment]
So the last piece of the puzzle is that the code is doing a DNS lookup on the hostname and we need to prove if that is working or not on your machines. Are you able to add the DNS lookup to the console application you made to see if it returns a result?

**Comment by DJBenson** [comment]
Or remove -Identity altogether if indeed it’s superfluous.

**Comment by mattidp** [comment]
That seems like the way to go. My servers all resolve their hostnames to their IP’s correctly, but I’m not sure how or why you are doing an unnecessary DNS lookup that could fail in certain environments.

I would think you would just query the environment var for COMPUTERNAME IF it was truly needed.

**Comment by DJBenson** [comment]
Not sure as to why it’s done that way but I’ll take a look tomorrow and see if we can do something different.

**Comment by DJBenson** [comment]
OK so I had a look at the code and put the debug on the Get-ExchangeServer call and it's just returning the NETBIOS name of the machine (so in my case MAIL01)

![Dns GetHostNameOutput](https://user-images.githubusercontent.com/1013909/71965569-d8129100-31f7-11ea-9584-a2d1692f03ab.png)

I've removed the Dns.GetHostName from the call and simply calling the below still works in my environment (Exchange 2019 CU4):
>Get-ExchangeServer | fl AdminDisplayVersion

This is a test build with the amended Get-ExchangeServer call, see if it works for you:  
>[Configuration.DkimSigner.zip](https://github.com/Pro/dkim-exchange/files/4034497/Configuration.DkimSigner.zip)

I'm not sure what downstream impact removing the Dns.GetHostName call will have so if this does launch in your environment I'm going to put the call back in then add a secondary call if the first fails and only then drop out with the error about not being able to determine the Exchange version - there must be a good reason why the -Identity parameter was being passed and I've not had time to investigate yet.

**Comment by DJBenson** [comment]
Ah I can see why -Identity is required now. If you call
>Get-ExchangeServer

and you have multiple exchange servers in your environment, you will get a list back of all the servers. You need to pass -Identity to return only the server on which Exchange DKIM Signer is running.

[Source](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/Get-ExchangeServer).

**Comment by boscorelly** [comment]
> [PS] C:\Windows>Get-ExchangeServer -Identity | fl AdminDisplayVersion
> 
> Get-ExchangeServer : Missing an argument for parameter 'Identity'. 
> Specify a parameter of type 'System.Object' and try
> again.
> At line:1 char:29
> + Get-ExchangeServer -Identity <<<< | fl AdminDisplayVersion
> + CategoryInfo : InvalidArgument: (:) [Get-ExchangeServer], 
> ParameterBindingException
> + FullyQualifiedErrorId : MissingArgument,Get-ExchangeServer

With try to tweeak Exchange if you don't know the how cmdlets work ?!...

**Comment by DJBenson** [comment]
> [PS] C:\Windows>Get-ExchangeServer -Identity | fl AdminDisplayVersion Get-ExchangeServer : Missing an argument for parameter 'Identity'. Specify a parameter of type 'System.Object' and try again. At line:1 char:29 + Get-ExchangeServer -Identity <<<< | fl AdminDisplayVersion + CategoryInfo : InvalidArgument: (:) [Get-ExchangeServer], ParameterBindingException + FullyQualifiedErrorId : MissingArgument,Get-ExchangeServer
> With try to tweeak Exchange if you don't know the how cmdlets work ?!...

Refer to my [reply](https://github.com/Pro/dkim-exchange/issues/266#issuecomment-571873410) above - GitHub stripped some of the Get-ExchangeServer command in [this](https://github.com/Pro/dkim-exchange/issues/266#issuecomment-571866456) post so @mattidp  only ran what I asked him to run - it was only afterwards I realised GitHub had dropped the "HOSTNAME" part of the command (as it was inbetween \< and > characters).

**Comment by boscorelly** [comment]
> Refer to my reply 

i've seen. But if you know what you are doing, you see the -identity and 
know how exchange cmdlets works... It's a basic ! (and mostly, -identity 
is present in 99.99% in exchange cmdlets !)

**Comment by DJBenson** [comment]
> Refer to my reply
> i've seen. But if you know what you are doing, you see the -identity and know how exchange cmdlets works... It's a basic ! (and mostly, -identity is present in 99.99% in exchange cmdlets !)

Thanks for your input.

**Comment by mattidp** [comment]
Thanks for trying to help! Doesn't work unfortunately. I think we've eliminated the powershell command syntax as being an issue.  

I think the issue must NOT be related to the valid powershell commands but 
"initializing the powershell runspace" as the error message I posted indicates (ALL powershell command).  I've done a lot of programming but never delved into code initialization of the powershell runspace which is where our problem is, in certain environments like mine.

Thanks again for your time and effort!

**Comment by rbfajardo** [comment]
@DJBenson There is an exception being swallowed in ExecPowerShellCommand() in PowerShellHelper class (Line 50). I think if you return this either as an inner exception or log to event log it would expose the underlying problem.

**Comment by mattidp** [comment]
Thanks! I’ll give that a try soon.

-Matt

**Comment by envegter** [comment]
I experience the same Transport Service not starting (crashing) on Exchange 2019 CU4 and CU5.
Installation and configuration of the current (v3.2.4) are fine and exchange 2019 servers are detected.
The exchange transport fails to start and crashes repetitively and end-up in 'Stopping' state.
I tested on 2 separate exchange 2019CU5 installations. 
Exchange CU5 running on Windows 2019 and dotnet 4.8. All latest patches applied.
