### ISSUE TITLE
Configure domains on core server 2019

### ISSUE THREAD

**Issue by gabor-au** [Pro/dkim-exchange#309]
### Versions

- **Windows Server Version**: Server 2019 Core Standard
- **Exchange Version**: Exchange 2019 Standard RTM
- **Installed DKIM Exchange Version**: 3.2.6

### Description

Issue when adding a domain to the DKIM signer. 
When either trying to generate a new key or selecting an existing key, the application throws an error. It looks like the error is due to unable to open a file browser window in Server core.

This is the error stack:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.Windows.Forms.OpenFileDialog.CreateVistaDialog()
   at System.Windows.Forms.FileDialog.RunDialogVista(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at Configuration.DkimSigner.MainWindow.btDomainKeySelect_Click(Object sender, EventArgs e) in C:\Users\jonathan.thomson\Documents\GitHub\dkim-exchange\Src\Configuration.DkimSigner\MainWindow.cs:line 971
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3640.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Configuration.DkimSigner
    Assembly Version: 3.2.6.0
    Win32 Version: 3.2.6
    CodeBase: file:///C:/Program%20Files/Exchange%20DkimSigner/Configuration.DkimSigner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3580.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3640.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3630.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3640.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3620.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1007
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
----------------------------------------
Microsoft.PowerShell.Commands.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.PowerShell.Security
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
----------------------------------------
Microsoft.WSMan.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.348
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3630.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3640.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.Exchange.PowerShell.Configuration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PowerShell.Configuration.dll
----------------------------------------
Microsoft.Exchange.Data.Directory
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Directory.DLL
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3620.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3620.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.Exchange.Diagnostics
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Diagnostics.DLL
----------------------------------------
Microsoft.Exchange.Data
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.DLL
----------------------------------------
Microsoft.Exchange.Net
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Net.DLL
----------------------------------------
Microsoft.Exchange.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.DLL
----------------------------------------
Microsoft.Exchange.Data.Common
    Assembly Version: 15.2.216.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Common/v4.0_15.2.216.0__31bf3856ad364e35/Microsoft.Exchange.Data.Common.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3640.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.Exchange.Management.Transport
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Transport.DLL
----------------------------------------
Microsoft.Exchange.Configuration.ObjectModel
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.ObjectModel.DLL
----------------------------------------
Microsoft.Exchange.Management.Recipient
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Recipient.DLL
----------------------------------------
Microsoft.Exchange.Management
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.DLL
----------------------------------------
Microsoft.Exchange.Data.Transport
    Assembly Version: 15.2.216.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Exchange.Data.Transport/v4.0_15.2.216.0__31bf3856ad364e35/Microsoft.Exchange.Data.Transport.dll
----------------------------------------
Microsoft.Exchange.Transport.Logging.Search
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Logging.Search.DLL
----------------------------------------
Microsoft.Exchange.Management.Powershell.Support
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Powershell.Support.DLL
----------------------------------------
Microsoft.Exchange.Rules.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Rules.Common.DLL
----------------------------------------
Microsoft.Exchange.MessagingPolicies.Rules
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessagingPolicies.Rules.DLL
----------------------------------------
Microsoft.Exchange.Management.Provisioning
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Provisioning.DLL
----------------------------------------
Microsoft.Exchange.MessageSecurity
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MessageSecurity.DLL
----------------------------------------
Microsoft.Exchange.StoreProvider
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.StoreProvider.DLL
----------------------------------------
Microsoft.Exchange.Management.Mobility
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Mobility.DLL
----------------------------------------
Microsoft.Exchange.Data.Storage
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Storage.DLL
----------------------------------------
Microsoft.Exchange.Management.Migration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.Migration.DLL
----------------------------------------
Microsoft.Exchange.MailboxReplicationService.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.MailboxReplicationService.Common.DLL
----------------------------------------
Microsoft.Exchange.Migration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Migration.DLL
----------------------------------------
Microsoft.Exchange.Data.MailboxLoadBalance
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.MailboxLoadBalance.DLL
----------------------------------------
Microsoft.Exchange.Data.Mapi
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Mapi.DLL
----------------------------------------
Microsoft.Exchange.Compliance.TaskDistributionCommon
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.TaskDistributionCommon.DLL
----------------------------------------
Microsoft.Exchange.Data.ApplicationLogic
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.ApplicationLogic.DLL
----------------------------------------
Microsoft.Office.CompliancePolicy.Platform
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Office.CompliancePolicy.Platform.DLL
----------------------------------------
Microsoft.Exchange.Data.StoreObjects
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.StoreObjects.DLL
----------------------------------------
Microsoft.Exchange.Transport.Sync.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Sync.Common.DLL
----------------------------------------
Microsoft.Exchange.Data.Providers
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Providers.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Exchange.Transport.Agent.InterceptorAgent
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.InterceptorAgent.DLL
----------------------------------------
Microsoft.Exchange.Transport.Agent.AntiSpam.Common
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Agent.AntiSpam.Common.DLL
----------------------------------------
Microsoft.Exchange.PswsClient
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PswsClient.DLL
----------------------------------------
Microsoft.Exchange.Management.CompliancePolicy
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Management.CompliancePolicy.DLL
----------------------------------------
Microsoft.Exchange.Configuration.RedirectionModule
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.RedirectionModule.DLL
----------------------------------------
Microsoft.Exchange.WorkloadManagement
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.WorkloadManagement.DLL
----------------------------------------
Microsoft.Exchange.Sqm
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Sqm.DLL
----------------------------------------
Microsoft.Exchange.Configuration.Core
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Configuration.Core.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration.ExCore
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.ExCore.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration.Core
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.Core.DLL
----------------------------------------
Microsoft.Search.Platform.Parallax
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.4.0
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Search.Platform.Parallax.DLL
----------------------------------------
Microsoft.Exchange.VariantConfiguration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.dll
----------------------------------------
Microsoft.PowerShell.HostingTools
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.PowerShell.HostingTools.DLL
----------------------------------------
Microsoft.Exchange.Configuration.ObjectModel.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Configuration.ObjectModel.resources.DLL
----------------------------------------
Microsoft.Exchange.Data.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/hu/Microsoft.Exchange.Data.resources.DLL
----------------------------------------
Microsoft.Exchange.Common.Directory.DirectoryVariantConfig
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Common.Directory.DirectoryVariantConfig.DLL
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.Exchange.Extensibility.Internal
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Extensibility.Internal.DLL
----------------------------------------
Microsoft.Exchange.Transport.Flighting
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Transport.Flighting.dll
----------------------------------------
Microsoft.Exchange.Common.ComponentConfig.Transport
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/Microsoft.Exchange.Common.ComponentConfig.Transport.DLL
----------------------------------------
Microsoft.Exchange.Core.TimeZone
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Core.TimeZone.DLL
----------------------------------------
Microsoft.Exchange.Compliance
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Compliance.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Exchange.Core.TimeZone.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Core.TimeZone.resources.DLL
----------------------------------------
System.DirectoryServices.Protocols
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.Protocols/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.Protocols.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Microsoft.Exchange.ProvisioningAgent
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/Bin/CmdletExtensionAgents/Microsoft.Exchange.ProvisioningAgent.dll
----------------------------------------
Microsoft.Exchange.VariantConfiguration.GlobalSettings
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.VariantConfiguration.GlobalSettings.DLL
----------------------------------------
Microsoft.Exchange.Data.resources
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/en/Microsoft.Exchange.Data.resources.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Exchange.Transport.Extensibility
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0221.012
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Transport.Extensibility.DLL
----------------------------------------
BouncyCastle
    Assembly Version: 1.8.1.0
    Win32 Version: 1.8.15362.1
    CodeBase: file:///C:/Program%20Files/Exchange%20DkimSigner/BouncyCastle.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

### Steps to Reproduce

1. Open DKIM signer
2. Go to Domain settings tab
3. Add new domain
4. Specify the domain name
5. Specify the selector
6. Click Generate new file or Select key file -> app throws the above error

**Expected behavior:** Should be able to generate a key or select an existing key (it works on non core exhcnage servers for me for other organization)

**Actual behavior:** File browsing window doesn't open, unable to select/save/specify existing file.

Thank you for your help in advance.
Regards
Gabor

**Comment by gabor-au** [comment]
Temporarily I found a workaround by generating a new key file on a non-core server and copying it over to the core server and manually modifying the settings.xml file based on a working version on the non-core server.
